/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscribeUnsubscribeRouteImport } from './routes/subscribe.unsubscribe'
import { Route as SubscribeConfirmRouteImport } from './routes/subscribe.confirm'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as CompanyCompanyKeyRouteImport } from './routes/company.$companyKey'
import { Route as ChangelogFeedDotxmlRouteImport } from './routes/changelog.feed[.]xml'
import { Route as ApiCronWatchdogRouteImport } from './routes/api.cron.watchdog'

const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeUnsubscribeRoute = SubscribeUnsubscribeRouteImport.update({
  id: '/subscribe/unsubscribe',
  path: '/subscribe/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeConfirmRoute = SubscribeConfirmRouteImport.update({
  id: '/subscribe/confirm',
  path: '/subscribe/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyKeyRoute = CompanyCompanyKeyRouteImport.update({
  id: '/company/$companyKey',
  path: '/company/$companyKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogFeedDotxmlRoute = ChangelogFeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => ChangelogRoute,
} as any)
const ApiCronWatchdogRoute = ApiCronWatchdogRouteImport.update({
  id: '/api/cron/watchdog',
  path: '/api/cron/watchdog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/changelog/feed.xml': typeof ChangelogFeedDotxmlRoute
  '/company/$companyKey': typeof CompanyCompanyKeyRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/subscribe/confirm': typeof SubscribeConfirmRoute
  '/subscribe/unsubscribe': typeof SubscribeUnsubscribeRoute
  '/api/cron/watchdog': typeof ApiCronWatchdogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/changelog/feed.xml': typeof ChangelogFeedDotxmlRoute
  '/company/$companyKey': typeof CompanyCompanyKeyRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/subscribe/confirm': typeof SubscribeConfirmRoute
  '/subscribe/unsubscribe': typeof SubscribeUnsubscribeRoute
  '/api/cron/watchdog': typeof ApiCronWatchdogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/changelog/feed.xml': typeof ChangelogFeedDotxmlRoute
  '/company/$companyKey': typeof CompanyCompanyKeyRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/subscribe/confirm': typeof SubscribeConfirmRoute
  '/subscribe/unsubscribe': typeof SubscribeUnsubscribeRoute
  '/api/cron/watchdog': typeof ApiCronWatchdogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/changelog'
    | '/methodology'
    | '/changelog/feed.xml'
    | '/company/$companyKey'
    | '/sitemap/xml'
    | '/subscribe/confirm'
    | '/subscribe/unsubscribe'
    | '/api/cron/watchdog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/changelog'
    | '/methodology'
    | '/changelog/feed.xml'
    | '/company/$companyKey'
    | '/sitemap/xml'
    | '/subscribe/confirm'
    | '/subscribe/unsubscribe'
    | '/api/cron/watchdog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/changelog'
    | '/methodology'
    | '/changelog/feed.xml'
    | '/company/$companyKey'
    | '/sitemap/xml'
    | '/subscribe/confirm'
    | '/subscribe/unsubscribe'
    | '/api/cron/watchdog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangelogRoute: typeof ChangelogRouteWithChildren
  MethodologyRoute: typeof MethodologyRoute
  CompanyCompanyKeyRoute: typeof CompanyCompanyKeyRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  SubscribeConfirmRoute: typeof SubscribeConfirmRoute
  SubscribeUnsubscribeRoute: typeof SubscribeUnsubscribeRoute
  ApiCronWatchdogRoute: typeof ApiCronWatchdogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/unsubscribe': {
      id: '/subscribe/unsubscribe'
      path: '/subscribe/unsubscribe'
      fullPath: '/subscribe/unsubscribe'
      preLoaderRoute: typeof SubscribeUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/confirm': {
      id: '/subscribe/confirm'
      path: '/subscribe/confirm'
      fullPath: '/subscribe/confirm'
      preLoaderRoute: typeof SubscribeConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyKey': {
      id: '/company/$companyKey'
      path: '/company/$companyKey'
      fullPath: '/company/$companyKey'
      preLoaderRoute: typeof CompanyCompanyKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/feed.xml': {
      id: '/changelog/feed.xml'
      path: '/feed.xml'
      fullPath: '/changelog/feed.xml'
      preLoaderRoute: typeof ChangelogFeedDotxmlRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/api/cron/watchdog': {
      id: '/api/cron/watchdog'
      path: '/api/cron/watchdog'
      fullPath: '/api/cron/watchdog'
      preLoaderRoute: typeof ApiCronWatchdogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChangelogRouteChildren {
  ChangelogFeedDotxmlRoute: typeof ChangelogFeedDotxmlRoute
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogFeedDotxmlRoute: ChangelogFeedDotxmlRoute,
}

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangelogRoute: ChangelogRouteWithChildren,
  MethodologyRoute: MethodologyRoute,
  CompanyCompanyKeyRoute: CompanyCompanyKeyRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  SubscribeConfirmRoute: SubscribeConfirmRoute,
  SubscribeUnsubscribeRoute: SubscribeUnsubscribeRoute,
  ApiCronWatchdogRoute: ApiCronWatchdogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
