/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyCompanyKeyRouteImport } from './routes/company.$companyKey'

const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyKeyRoute = CompanyCompanyKeyRouteImport.update({
  id: '/company/$companyKey',
  path: '/company/$companyKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/company/$companyKey': typeof CompanyCompanyKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/company/$companyKey': typeof CompanyCompanyKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/company/$companyKey': typeof CompanyCompanyKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/methodology' | '/company/$companyKey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/methodology' | '/company/$companyKey'
  id: '__root__' | '/' | '/methodology' | '/company/$companyKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodologyRoute: typeof MethodologyRoute
  CompanyCompanyKeyRoute: typeof CompanyCompanyKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyKey': {
      id: '/company/$companyKey'
      path: '/company/$companyKey'
      fullPath: '/company/$companyKey'
      preLoaderRoute: typeof CompanyCompanyKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodologyRoute: MethodologyRoute,
  CompanyCompanyKeyRoute: CompanyCompanyKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
