/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyCompanyKeyRouteImport } from './routes/company.$companyKey'
import { Route as ChangelogFeedDotxmlRouteImport } from './routes/changelog.feed[.]xml'

const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyKeyRoute = CompanyCompanyKeyRouteImport.update({
  id: '/company/$companyKey',
  path: '/company/$companyKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogFeedDotxmlRoute = ChangelogFeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => ChangelogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/changelog/feed.xml': typeof ChangelogFeedDotxmlRoute
  '/company/$companyKey': typeof CompanyCompanyKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/changelog/feed.xml': typeof ChangelogFeedDotxmlRoute
  '/company/$companyKey': typeof CompanyCompanyKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/changelog/feed.xml': typeof ChangelogFeedDotxmlRoute
  '/company/$companyKey': typeof CompanyCompanyKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/methodology'
    | '/changelog/feed.xml'
    | '/company/$companyKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/methodology'
    | '/changelog/feed.xml'
    | '/company/$companyKey'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/methodology'
    | '/changelog/feed.xml'
    | '/company/$companyKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRouteWithChildren
  MethodologyRoute: typeof MethodologyRoute
  CompanyCompanyKeyRoute: typeof CompanyCompanyKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyKey': {
      id: '/company/$companyKey'
      path: '/company/$companyKey'
      fullPath: '/company/$companyKey'
      preLoaderRoute: typeof CompanyCompanyKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/feed.xml': {
      id: '/changelog/feed.xml'
      path: '/feed.xml'
      fullPath: '/changelog/feed.xml'
      preLoaderRoute: typeof ChangelogFeedDotxmlRouteImport
      parentRoute: typeof ChangelogRoute
    }
  }
}

interface ChangelogRouteChildren {
  ChangelogFeedDotxmlRoute: typeof ChangelogFeedDotxmlRoute
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogFeedDotxmlRoute: ChangelogFeedDotxmlRoute,
}

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRouteWithChildren,
  MethodologyRoute: MethodologyRoute,
  CompanyCompanyKeyRoute: CompanyCompanyKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
